chain: "bitcoin-testnet"
grpcPort: 9093
grpcProxyPort: 9094
interval: 1m
batchSize: 10
database:
  uri: ""
  driver: "mysql"
cashiers:
  - id: "bitcoin-testnet-to-iotex"
    relayerURL: ":7001"
    startBlockHeight:
    validatorContractAddress: ""
    cashierContractAddress: ""
    tokenSafeContractAddress: ""
    transferTableName: "bitcoin_testnet_transfers"
    minTipFee: 100
confirmBlockNumber: 3
