chain: "iotex"
grpcPort: 9320
grpcProxyPort: 9321
interval: 30s
batchSize: 1000
database:
  uri: "root:kdfjjrU64fjK58H@tcp(localhost:13306)/witness?parseTime=true"
  driver: "mysql"
cashiers:
  - id: "iotex-to-solana"
    relayerURL: ":7007"
    startBlockHeight: 
    validatorContractAddress: ""
    cashierContractAddress: ""
    transferTableName: "iotex_transfers"
    tokenPairs:
      - token1: ""
        token2: ""
destinationChain: "solana"