chain: "polis"
clientURL: "https://rpc.polis.tech"
grpcPort: 9090
grpcProxyPort: 9091
privateKey: ""
slackWebHook: ""
interval: 1m
batchSize: 40
database:
  uri: "root:kdfjjrU64fjK58H@tcp(localhost:13306)/witness?parseTime=true"
  driver: "mysql"
cashiers:
  - id: "polis-to-iotex"
    relayerURL: "localhost:7001"
    startBlockHeight: 2567000
    validatorContractAddress: "io10xr64as4krm5nufd5l2ddc43al6tl0smumkg7y"
    cashierContractAddress: "0x089B44FDBC953fe80Ad1f5059573b96a4713e4b4"
    transferTableName: "polis_transfers"
    tokenPairs:
